import { Metadata } from "next";
import Header from "./components/Header";
import "./globals.css";
import Providers from "./pages/_app";

// Export metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <Providers> {/* Wrap your app with Redux provider here */}
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
